# Generated by Django 2.1.4 on 2018-12-30 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
